typo: at line 229, 249, 321
X-lab2017/oss101 pull request #100
Opened 2023-04-17 11:43 UTC by Philosober

2023-04-17 12:04 UTC, TieWay59 requested changes
你们的标题和你们实际提交的变更没有完全对上，请再检查一下。

2023-04-17 12:27 UTC, Philosober commented
> 你们的标题和你们实际提交的变更没有完全对上，请再检查一下。

已改

2023-04-17 12:38 UTC, TieWay59 commented on Assignments/Assignment-typo.md
> +There is one limited exception to this rule. If you think the question is such that you are likely to get many answers that are all closely similar, then the magic words are “e-mail me and I'll summa
这里引入了一些不必要的变更，需要去除。

2023-04-17 13:26 UTC, Philosober commented on Assignments/Assignment-typo.md
> +There is one limited exception to this rule. If you think the question is such that you are likely to get many answers that are all closely similar, then the magic words are “e-mail me and I'll summa
@xunx911 需要去除

2023-04-17 14:19 UTC, TieWay59 requested changes

2023-04-17 14:19 UTC, TieWay59 commented on Assignments/Assignment-typo.md
> +There is one limited exception to this rule. If you think the question is such that you are likely to get many answers that are all closely similar, then the magic words are "e-mail me and I'll summa
还有一处空格被修改了。

2023-04-18 03:53 UTC, TieWay59 approved these changes

2023-04-22 14:15 UTC, merged