typo: `channelsfrom` at line 87,`mai ling` at line 89, `youan` at line 93
X-lab2017/oss101 pull request #147
Opened 2023-05-12 05:46 UTC by yuanam

2023-05-12 06:21 UTC, yuanam commented
- Fix Skip space typo `channelsfrom` at line 87
- Fix extra space typo `mai ling` at line 89
- Fix Skip space typo `youan` at line 93
team: 10205501403 10205501404 10205501418 11205501401

2023-05-12 07:26 UTC, TieWay59 commented
hi @yuanam ，你可以点击右上角三个点修改 PR 正文。

2023-05-12 07:27 UTC, TieWay59 requested changes
需要想办法去掉这两个commit哦！

2023-05-13 05:26 UTC, TieWay59 approved these changes

2023-05-13 11:02 UTC, merged