typo: daysor at line 149, that, at line 29, mess age at line 101, inyour at line 151, dpends at line 19, friend at line 89.
X-lab2017/oss101 pull request #178
Opened 2023-05-15 07:33 UTC by Jalingpp

2023-05-15 08:33 UTC, qqliang commented
fix https://github.com/X-lab2017/oss101/issues/71

fix skip space typo: 'daysor' at line 149 to 'days or'.
fix extra letter typo: 'that,' at line 29 to 'that'.
fix extra space typo: 'mess age' at line 101 to 'message'.
fix skip space typo: 'inyour' at line 151 to 'in your'.
fix wrong letter typo: 'dpends' at line 19 to 'depends'.
fix wrong letter typo: 'friend' at line 89 to 'friends'.
team: 52265903004 52265903003 51255903082 51255903065

2023-05-22 10:34 UTC, TieWay59 requested changes
![image](https://github.com/X-lab2017/oss101/assets/40034603/d7158d76-21b0-4572-a217-9785083152c5)
不应该有这么多行的修改。

2023-05-23 02:04 UTC, TieWay59 requested changes

2023-05-23 02:04 UTC, TieWay59 commented on Assignments/Assignment-typo.md
> +We realize that there are many people who just want to use the software we write, and who have no interest in learning technical details. For most people, a computer is merely a tool, a means to an e
我们不包含修改逗号的。

2023-05-23 02:04 UTC, TieWay59 commented on .github/workflows/add-reaction.yaml
> +          "Jalingpp",
这个修改请放在其他 PR 。

2023-05-23 02:06 UTC, TieWay59 commented
如果你们实在找不到的话，我可以支持你们只需要两处typo，把那个不合适的去掉就好了。

2023-05-23 02:10 UTC, closed without merging