ci: add `qqliang` to reaction list~
X-lab2017/oss101 pull request #180
Opened 2023-05-15 09:21 UTC by qqliang

ci: add qqliang to reaction list~

2023-05-17 01:53 UTC, TieWay59 requested changes
本 PR 只能包含一个commit并且只对一个文件的一行进行修改。其他105行的修改是不应该出现的。你可以通过 `git rebase -i HEAD~5` 重新整理你的commit。

2023-05-21 03:08 UTC, qqliang commented
> 本 PR 只能包含一个commit并且只对一个文件的一行进行修改。其他105行的修改是不应该出现的。你可以通过 `git rebase -i HEAD~5` 重新整理你的commit。

以按照要求重新整理了commit

2023-05-22 02:17 UTC, TieWay59 commented
@qqliang  因为过去的时间比较久，请你及时再更新一次，我下面优先合你的。

2023-05-22 02:32 UTC, qqliang commented
> @qqliang 因为过去的时间比较久，请你及时再更新一次，我下面优先合你的。

我以重新提交，但提示 Can’t automatically merge.

2023-05-22 13:43 UTC, TieWay59 commented
而且，你最好调整一下你的git remote 中的upstream改成我们课程主仓库。

2023-05-22 13:45 UTC, qqliang commented
> > > @qqliang 因为过去的时间比较久，请你及时再更新一次，我下面优先合你的。
> > 
> > 
> > 我已重新提交，但提示 Can’t automatically merge.
> 
> 我不知道你做了什么操作，但是据我所知github上没有一步到位的简单处理方法。我的建议是在你本地借助reset去掉已有的 commit，然后从上游pull main分支，然后再把你的内容加进去，随后强制推送。

我就是这样做的，直接git fetch upstream，拉取原仓库最新状态，然后直接git reset --hard upstream/main覆盖本地内容，再把自己的名字加上去，用git push --force强制更新到我的远程仓库上。

2023-05-22 13:48 UTC, qqliang commented
> 而且，你最好调整一下你的git remote 中的upstream改成我们课程主仓库。

本地仓库的git remote的upstream就是x-lab主仓库。

`$ git remote -v
origin  git@github.com:qqliang/oss101.git (fetch)
origin  git@github.com:qqliang/oss101.git (push)
upstream        git@github.com:X-lab2017/oss101.git (fetch)
upstream        git@github.com:X-lab2017/oss101.git (push)`

2023-05-22 14:04 UTC, qqliang commented
> > > > @qqliang 因为过去的时间比较久，请你及时再更新一次，我下面优先合你的。
> > > 
> > > 
> > > 我已重新提交，但提示 Can’t automatically merge.
> > 
> > 
> > 我不知道你做了什么操作，但是据我所知github上没有一步到位的简单处理方法。我的建议是在你本地借助reset去掉已有的 commit，然后从上游pull main分支，然后再把你的内容加进去，随后强制推送。
> 
> 我就是这样做的，直接git fetch upstream，拉取原仓库最新状态，然后直接git reset --hard upstream/main覆盖本地内容，再把自己的名字加上去，用git push --force强制更新到我的远程仓库上。

我再按照上面的操作重新执行了一遍，这次在pull request的状态中显示“able to merge”了。出现上面的错误可能还是因为我在操作的过程中又落后了一个版本，导致合并冲突吧。

2023-05-22 14:08 UTC, TieWay59 commented
> > > > > @qqliang 因为过去的时间比较久，请你及时再更新一次，我下面优先合你的。
> > > > 
> > > > 
> > > > 我已重新提交，但提示 Can’t automatically merge.
> > > 
> > > 
> > > 我不知道你做了什么操作，但是据我所知github上没有一步到位的简单处理方法。我的建议是在你本地借助reset去掉已有的 commit，然后从上游pull main分支，然后再把你的内容加进去，随后强制推送。
> > 
> > 
> > 我就是这样做的，直接git fetch upstream，拉取原仓库最新状态，然后直接git reset --hard upstream/main覆盖本地内容，再把自己的名字加上去，用git push --force强制更新到我的远程仓库上。
> 
> 我再按照上面的操作重新执行了一遍，这次在pull request的状态中显示“able to merge”了。出现上面的错误可能还是因为我在操作的过程中又落后了一个版本，导致合并冲突吧。

好的，我也觉得你的思路没问题。

2023-05-22 14:09 UTC, TieWay59 approved these changes
LGTM

2023-05-22 14:09 UTC, merged