fix extra space typo 'sep arate' at line 275 to 'separate',
X-lab2017/oss101 pull request #85
Opened 2023-04-17 07:56 UTC by Tamiflu233

- fix extra space typo 'sep arate' at line 275 to 'separate'
- fix extra space typo ques tions line 111 to questions
- fix skip letter typoPeope line 27 to People
51255903015 51255903014 51255903062  52275903004

2023-04-17 09:22 UTC, TieWay59 requested changes

2023-04-17 09:22 UTC, TieWay59 commented on Assignments/Assignment-typo.md
> +What we are, unapologetically, is hostile to people who seem to be unwilling to think or to do their own homework before asking questions. People like that are time sinks --- they take without giving
标题中没有提到这两处变更，我建议放弃这两处让给其他同学。

2023-04-25 03:17 UTC, Tamiflu233 commented on Assignments/Assignment-typo.md
> +What we are, unapologetically, is hostile to people who seem to be unwilling to think or to do their own homework before asking questions. People like that are time sinks --- they take without giving
我们这里rebase好了，看看可以吗

2023-04-25 08:11 UTC, Tamiflu233 commented
已修改

2023-04-25 09:43 UTC, merged